import { faSquareXmark } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {useRef} from 'react'
import useClickOutside from "../../hook/useClickOutside"

export default function CguModal({cgu, setCgu, setConfidentialModal}){
    const containerRef = useRef(null)
    useClickOutside(containerRef, cgu, setCgu)
    return (
        <div className="fixed h-screen w-screen bg-opacity-40 bg-black overflow-y-hidden overflow-x-hidden z-[200]">
            <div className="relative h-full w-full">
                <div className=" h-full w-full md:h-[85%] md:w-[50%] absolute left-2/4 top-2/4 transform -translate-x-2/4 -translate-y-2/4 bg-white md:p-10 overflow-y-auto space-y-4 rounded"
                ref={containerRef}>
                    <div className="flex justify-between w-full items-center md:-mt-5 mt-2 px-4">
                        <h2 className="text-lg font-semibold text-dark-blue">CGU</h2>
                        <div className="text-light-green text-[30px] md:-mr-2 " onClick={() => setCgu(false)}><FontAwesomeIcon icon={faSquareXmark}/></div>
                    </div>
                    <div><p className="text-light-green text-[15px] p-3">Date de dernière mise à jour : 30 juin 2022</p></div>
                    <div className="space-y-5 p-3 md:p-0" >
                        <p className="text-[17px] leading-[40px] text-dark-blue"><b>Article 1 – Le site</b></p>
                        <p className="text-[17px] leading-[40px] text-dark-blue">Le présent site, accessible à l’URL www.artisan-pac.info (ci-après le « Site »), est édité par : Société STEP UP DIGITAL, Société par Action Simplifiée au capital de 1000,00 €, immatriculée au RCS de Bobigny sous le numéro 831 726 559 dont le siège social est situé au 29 rue Cartier Bresson 93500 PANTIN et le numéro TVA FR 92831726559, représentée par Monsieur Andy TEBOUL, en sa qualité de Président. (Ci-après désigné l’« Exploitant »).</p>
                        <p className="text-[17px] leading-[40px] text-dark-blue"><b>Article 2 – DESCRIPTION DU SERVICE</b></p>
                        <p className="text-[17px] leading-[40px] text-dark-blue">Le Site est mis à la disposition de toute personne accédant au site (ci-après l’«Utilisateur ») pour découvrir les services proposés par l’Exploitant, le contacter ou souscrire à la Newsletter. Le Site ne propose pas de transaction commerciale. Si l’Utilisateur est intéressé par le service proposé par l’Exploitant, il doit prendre contact avec l’Exploitant pour connaître ses Condition Générales de Vente. L’Utilisateur demeure responsable des modalités et des conséquences de son accès au Site notamment par l’Internet. Cet accès peut impliquer le paiement de frais à des prestataires techniques tels que notamment des fournisseurs d’accès à l’Internet, lesquels demeurent à sa charge. En outre, l’Utilisateur devra fournir et être entièrement responsable des équipements nécessaires afin de se connecter au Site. L’Utilisateur reconnait avoir vérifié que la configuration informatique qu’il utilise est sécurisée et en état de fonctionnement. Les informations et services proposés par le Site sont gratuits, et accessibles 24h/24h et 7jours/7 jours, sauf en cas de force majeure, de pannes informatiques, d’opérations de maintenance ou de problèmes liés aux réseaux de télécommunications.</p>
                        <p className="text-[17px] leading-[40px] text-dark-blue"><b>Article 3 – PROPRIÉTÉ INTELLECTUELLE ET LICENCE D’UTILISATION DU SITE</b></p>
                        <p className="text-[17px] leading-[40px] text-dark-blue">L’Exploitant est seul titulaire de tous les éléments présents sur le Site, notamment et sans limitation, tous textes, fichiers, images animées ou non, photographies, vidéos, logos, dessins, modèles, logiciels, marques, identité visuelle, base de données, structure du Site et tous autres éléments de propriété intellectuelle et autres données ou informations (ci-après, les « Éléments ») qui sont protégés par les lois et règlements français et internationaux relatifs notamment à la propriété intellectuelle. En conséquence, aucun des Éléments du Site ne pourra en tout ou partie être modifié, reproduit, copié, dupliqué, vendu, revendu, transmis, publié, communiqué, distribué, diffusé, représenté, stocké, utilisé, loué ou exploité de toute autre manière, à titre gratuit ou onéreux, par un Utilisateur ou par un tiers, quel que soient les moyens et/ou les supports utilisés, qu’ils soient connus ou inconnus à ce jour, sans l’autorisation préalable exprès et écrite de l’Exploitant au cas par cas, et l’Utilisateur est seul responsable de toute utilisation et/ou exploitation non autorisée.</p>
                        <p className="text-[17px] leading-[40px] text-dark-blue"><b>ARTICLE 4 – RESPONSABILITÉ ET GARANTIE</b></p>
                        <p className="text-[17px] leading-[40px] text-dark-blue">L’Utilisateur reconnaît que les caractéristiques et les contraintes d’Internet ne permettent pas de garantir la sécurité, la disponibilité et l’intégrité des transmissions de données sur Internet. Ainsi, l’Exploitant ne garantit pas que le Site et ses services fonctionneront sans interruption ni erreur de fonctionnement. En particulier, leur exploitation pourra être momentanément interrompue pour cause de maintenance, de mises à jour ou d’améliorations techniques, ou pour en faire évoluer le contenu et/ou leur présentation. L’Exploitant ne peut être tenu pour responsable de l’utilisation qui serait faite du Site et de ses Éléments par les Utilisateurs en violation des présentes Conditions Générales d’Utilisation et des dommages directs ou indirects que cette utilisation pourrait causer à un Utilisateur ou à un tiers. En particulier, l’Exploitant ne peut être tenu pour responsable des fausses déclarations faites par un Utilisateur et de son comportement vis-à-vis des tiers. Dans le cas où la responsabilité de l’Exploitant serait recherchée à raison d’un tel comportement d’un de ses Utilisateurs, ce dernier s’engage à garantir l’Exploitant contre toute condamnation prononcée à son encontre ainsi qu’à rembourser l’Exploitant de l’ensemble des frais, notamment les honoraires d’avocats, engagés pour sa défense.</p>
                        <p className="text-[17px] leading-[40px] text-dark-blue"><b>ARTICLE 5 – DONNÉES A CARACTERE PERSONNEL</b></p>
                        <p className="text-[17px] leading-[40px] text-dark-blue"><span>Pour toute information concernant l’utilisation de données à caractère personnel par l’Exploitant, veuillez lire attentivement notre « Politique de confidentialité » accessible à <button className="text-[#0000ff] font-bold text-[20px]" onClick={() => {
                            setCgu(false)
                            setConfidentialModal(true)
                        }}>ici : </button></span><span>Vous pouvez à tout moment consulter la Politique de confidentialité sur le Site.</span></p>
                        <p className="text-[17px] leading-[40px] text-dark-blue"><b>Article 6 – LIENS HYPERTEXTES</b></p>
                        <p className="text-[17px] leading-[40px] text-dark-blue">Les liens hypertextes disponibles sur le Site peuvent renvoyer vers des sites tiers non édités par l’Exploitant. Ils sont fournis uniquement pour la convenance de l’Utilisateur, afin de faciliter l’utilisation des ressources disponibles sur l’Internet. Si l’Utilisateur utilise ces liens, il quittera le Site et acceptera alors d’utiliser les sites tiers à ses risques et périls ou le cas échéant conformément aux conditions qui les régissent. L’Utilisateur reconnait que l’Exploitant ne contrôle ni ne contribue en aucune manière à l’élaboration des conditions d’utilisation et/ou du contenu s’appliquant à ou figurant sur ces sites tiers. En conséquence, l’Exploitant ne saurait être tenu responsable de quelque façon que ce soit du fait de ces liens hypertextes En outre, l’Utilisateur reconnait que l’Exploitant ne saurait cautionner, garantir ou reprendre à son compte tout ou partie des conditions d’utilisation et/ou du contenu de ces sites tiers. Le Site peut également contenir des liens hypertextes promotionnels et/ou bandeaux publicitaires renvoyant vers des sites tiers non édités par l’Exploitant. L’Exploitant invite l’Utilisateur à lui signaler tout lien hypertexte présent sur le Site qui permettrait d’accéder à un site tiers proposant du contenu contraire aux lois et/ou aux bonnes mœurs. L’Utilisateur ne pourra pas utiliser et/ou insérer de lien hypertexte pointant vers le site sans l’accord écrit et préalable de l’Exploitant au cas par cas.</p>
                        <p className="text-[17px] leading-[40px] text-dark-blue"><b>ARTICLE 7 – DISPOSITION GÉNÉRALES</b></p>
                        <p className="text-[17px] leading-[40px] text-dark-blue">
                            <strong>INTEGRALITÉ DE L’ACCORD DES PARTIES</strong>
                            <br />
                            Les présentes Conditions Générales d’Utilisation constituent un contrat régissant les relations entre l’Utilisateur et l’Exploitant. Elles constituent l’intégralité des droits et obligations de l’Exploitant et de l’Utilisateur relatifs à leur objet. Si une ou plusieurs stipulations des présentes Conditions Générales d’Utilisation étaient déclarées nulles en application d’une loi, d’un règlement ou à la suite d’une décision définitive d’une juridiction compétente, les autres stipulations garderont toute leur force et leur portée. En outre, le fait pour une des parties aux présentes Conditions Générales d’Utilisation de ne pas se prévaloir d’un manquement de l’autre partie à l’une quelconque des dispositions des présentes Conditions Générales d’Utilisation ne saurait s’interpréter comme une renonciation de sa part à se prévaloir dans l’avenir d’un tel manquement. <br />
                            <strong>MODIFICATIONS DES CONDITIONS D’UTILISATION</strong> <br />
                            L’Exploitant se réserve le droit de modifier à tout moment et sans préavis le contenu du Site ou des services qui y sont disponibles, et/ou de cesser de manière temporaire ou définitive d’exploiter tout ou partie du Site. En outre, l’Exploitant se réserve le droit de modifier à tout moment et sans préavis la localisation du Site sur l’Internet, ainsi que les présentes Conditions Générales d’Utilisation. L’Utilisateur est donc tenu par conséquent de se reporter aux présentes Conditions Générales d’Utilisation avant toute utilisation du Site. En cas de modifications matérielles, l’Utilisateur sera informé au moyen d’un email et d’un avertissement sur le Site avant la mise en application de la modification. L’Utilisateur reconnait que l’Exploitant ne saurait être tenu responsable de quelque manière que ce soit envers lui ou tout tiers du fait de ces modifications, suspensions ou cessations. <br />
                            <strong>DROIT APPLICABLE</strong> <br />
                            Ces Conditions Générales d’Utilisation sont régies, interprétées et appliquées conformément au droit français.
                            <br />
                            <strong>ACCEPTATION DES CONDITIONS GÉNÉRALES PAR L’UTILISATEUR</strong>
                            <br />
                            Si l’Utilisateur décide de visite le Site, les présentes Conditions Générales d’Utilisation s’appliqueront automatiquement à son utilisation du Site. L’Utilisateur reconnait donc avoir pris connaissance des Conditions Générales d’Utilisation préalablement à son utilisation du Site, et déclare les accepter sans réserve. Les Conditions Générales d’Utilisation applicables à l’Utilisateur sont celles mises en ligne sur le Site. Le Site indiquera à l’Utilisateur que les présentes conditions générales ont été modifiées, l’Utilisateur devant se référer à la rubrique « CGU » pour vérifier les conditions générales en vigueur au moment de sa connexion.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    )
}