import { faSquareXmark } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {useRef} from 'react'
import useClickOutside from "../../hook/useClickOutside"

export default function ConfidentialModal({confidentialModal, setConfidentialModal}){
    const containerRef = useRef(null)
    useClickOutside(containerRef, confidentialModal, setConfidentialModal)

    return (
        <div className="fixed h-screen w-screen bg-opacity-40 bg-black overflow-y-hidden overflow-x-hidden z-[200]">
            <div className="relative h-full w-full">
                <div className=" h-full w-full md:h-[85%] md:w-[50%] absolute left-2/4 top-2/4 transform -translate-x-2/4 -translate-y-2/4 bg-white md:p-10 overflow-y-auto space-y-4 rounded"
                ref={containerRef}>
                    <div className="flex justify-between w-full items-center md:-mt-5 mt-2">
                        <h2 className="text-lg font-semibold text-dark-blue">Politique de confidentialité</h2>
                        <div className="text-light-green text-[30px] md:-mr-2 mr-2" onClick={() => setConfidentialModal(false)}><FontAwesomeIcon icon={faSquareXmark}/></div>
                    </div>
                    <div className="space-y-5 leading-[28px] p-3 md:p-0">
                        <p className="text-[28px] font-bold text-dark-blue"><b>Article 1 – PRÉAMBULE </b></p>
                        <p className="text-[17px] text-dark-blue">Cette politique de confidentialité s’applique au site : https://pac.optineo.info/ et à l’ensemble de ses sous-domaines. La présente politique de confidentialité a pour but d’exposer aux utilisateurs du site : La manière dont sont collectées et traitées leurs données à caractère personnel. Quels sont les droits des utilisateurs concernant ces données ; Qui est responsable du traitement des données à caractère personnel collectées et traitées ; A qui ces données sont transmises ; La politique du site en matière de fichiers « cookies ». Cette politique de confidentialité complète les mentions légales que les utilisateurs peuvent consulter sur le site web.</p>
                        <div className="text-[17px] text-dark-blue">Licéité, loyauté et transparence : les données ne peuvent être collectées et traitées qu’avec le consentement de l’utilisateur propriétaire des données. A chaque fois que des données à caractère personnel seront collectées, il sera indiqué à l’utilisateur que ses données sont collectées, et pour quelles raisons ses données sont collectées ; -Finalités limitées : la collecte et le traitement des données sont exécutés pour répondre à un ou plusieurs objectifs déterminés dans les présentes conditions générales d’utilisation ; -Minimisation de la collecte et du traitement des données : seules les données nécessaires à la bonne exécution des objectifs poursuivis par le site sont collectées ; -Conservation des données réduites dans le temps : les données sont conservées pour une durée limitée, dont l’utilisateur est informé; -Intégrité et confidentialité des données collectées et traitées : le responsable du traitement des données s’engage à garantir l’intégrité et la confidentialité des données collectées. Afin d’être licites, et ce conformément aux exigences de l’article 6 du règlement européen 2016/679, la collecte et le traitement des données à caractère personnel ne pourront intervenir que s’ils respectent au moins l’une des conditions ci-après énumérées : </div>
                        <ul className="list-disc ml-5">
                            <li className="text-[17px] text-dark-blue">L’utilisateur a expressément consenti au traitement ; </li>
                            <li className="text-[17px] text-dark-blue">Le traitement est nécessaire à la bonne exécution d’un contrat ; </li>
                            <li className="text-[17px] text-dark-blue">Le traitement répond à une obligation légale ; </li>
                            <li className="text-[17px] text-dark-blue">Le traitement s’explique par une nécessité liée à la sauvegarde des intérêts vitaux de la personne concernée ou d’une autre personne physique ; </li>
                            <li className="text-[17px] text-dark-blue">Le traitement peut s’expliquer par une nécessité liée à l’exécution d’une mission d’intérêt public ou qui relève de l’exercice de l’autorité publique ; </li>
                            <li className="text-[17px] text-dark-blue">Le traitement et la collecte des données à caractère personnel sont nécessaires aux fins des intérêts légitimes et privés poursuivis par le responsable du traitement ou par un tiers. Le fondement des traitements de données à caractère personnel objet de la présente politique de confidentialité est votre consentement. -Le traitement et la collecte des données à caractère personnel sont nécessaires aux fins des intérêts légitimes et privés poursuivis par le responsable du traitement ou par un tiers. Le fondement des traitements de données à caractère personnel objet de la présente politique de confidentialité est votre consentement. </li>
                        </ul>
                        <div className="text-[28px] font-bold text-dark-blue"><b> Article 3 – DONNÉES À CARACTÈRE PERSONNEL COLLECTÉES ET TRAITÉES DANS LE CADRE DE LA NAVIGATION SUR LE SITE </b></div>
                        <div className="text-[17px] text-dark-blue">Le responsable du traitement conservera les données collectées pour la finalité d’envoi de la Newsletter jusqu’à ce dans ses systèmes informatiques du site et dans des conditions raisonnables de sécurité l’ensemble des données collectées pour une durée maximum de 3 ans, pour les simples visites. </div>
                        <div className="text-[22px] font-bold text-dark-blue"><b> 3.1 – DONNÉES A CARACTERE PERSONNEL COLLECTÉES ET TRAITÉES </b></div>
                        <div className="text-[17px] text-dark-blue">Les données à caractère personnel collectées sur le site https://pac.optineo.info/ sont les suivantes : -Noms, prénom, adresse email, numéro de téléphone, données financières, localisation -Données de connexion adresses IP, informations d’horodatage </div>
                        <div className="text-[22px] font-bold text-dark-blue"><b> 3.2 – MODE DE COLLECTE DES DONNEES PERSONNELLES </b></div>
                        <div className="text-[17px] text-dark-blue">Ces données sont collectées lorsque l’utilisateur effectue l’une des opérations suivantes sur le site web: -Navigation sur le site internet : IP, informations d’horodatage -Inscription à une newsletter : noms, prénom, adresse email </div>
                        <div className="text-[28px] font-bold text-dark-blue"><b> Article 4 – FINALITE DU TRAITEMENT DES DONNEES A CARACTERE PERSONNEL </b></div>
                        <div className="text-[17px] text-dark-blue">La collecte et le traitement des données répondent notamment aux finalités suivantes : -Amélioration de la navigation -Envoi d’une Newsletter -Vous permettre l’envoi d’un message via le formulaire de contact du site </div>
                        <div className="text-[28px] font-bold text-dark-blue"><b>Article 5 – TRANSMISSION DES DONNÉES À DES TIERS</b></div>
                        <div className="text-[17px] text-dark-blue">Nous ne partagerons jamais, sans avoir obtenu votre consentement préalable, vos données à caractère personnel avec des sociétés tierces. Nous pouvons être amené à divulguer vos données à caractère personnel aux autorités administrative ou judiciaire lorsque leur divulgation est nécessaire à l’identification, l’interpellation ou la poursuite en justice de tout individu susceptible de porter préjudice à nos droits, de tout autre utilisateur ou d’un tiers. Nous pouvons enfin être légalement tenu de divulguer vos données à caractère personnel et ne pouvons dans ce cas nous y opposer. </div>
                        <div className="text-[28px] font-bold text-dark-blue"><b>Article 6 – HÉBERGEMENT DES DONNÉES</b></div>
                        <div className="text-[17px] text-dark-blue">Le site https://pac.optineo.info/ est hébergé par : OVH dont le siège est situé à l’adresse ci-après: 2 Rue Kellermann, 59100 Roubaix, France L’hébergeur peut être contacté au numéro de téléphone suivant : 1007 L’adresse email de l’hébergeur est support@ovh.fr Les données collectées et traitées par le site sont exclusivement hébergées et traitées dans les pays de l’Union européenne. </div>
                        <div className="text-[28px] font-bold text-dark-blue"><b>Article 7 – RESPONSABLE DU TRAITEMENT DES DONNÉES ET DÉLÉGUÉ À LA PROTECTION DES DONNÉES ;</b></div>
                        <div className="text-[22px] font-bold text-dark-blue"><strong>7.1 – LE RESPONSABLE DU TRAITEMENT DES DONNÉES</strong></div>
                        <div className="text-[17px] text-dark-blue">Le responsable du traitement des données à caractère personnel est la société STEP UP DIGITAL, SAS immatriculée sous le numéro 92831726559 au RCS de Bobigny, dont le siège social est situé au 29 rue Cartier Bresson 93500 PANTIN. Le responsable de traitement a désigné un Délégué à la protection des données. Il peut être contacté de la manière suivante : Par téléphone au 01 84 74 24 90 ou par email à dpo@stepup-digital.com </div>
                        <div className="text-[22px] font-bold text-dark-blue"><strong>7.2 – OBLIGATIONS DU RESPONSABLE DU TRAITEMENT DES DONNÉES</strong></div>
                        <div className="text-[17px] text-dark-blue">Le responsable du traitement s’engage à protéger les données à caractère personnel collectées, à ne pas les transmettre à des tiers sans que l’utilisateur n’en ait été informé et à respecter les finalités pour lesquelles ces données ont été collectées. Le site dispose d’un certificat SSL afin de garantir que les informations et le transfert des données transitant par le site sont sécurisés. Un certificat SSL (« Secure Socket Layer » Certificate) a pour but de sécuriser les données échangées entre l’utilisateur et le site. De plus, le responsable du traitement des données s’engage à notifier l’utilisateur en cas de rectification ou de suppression des données, à moins que cela n’entraîne pour lui des formalités, coûts et démarches disproportionnés. Dans le cas où l’intégrité, la confidentialité ou la sécurité des données à caractère personnel de l’utilisateur est compromise, le responsable du traitement s’engage à informer l’utilisateur par tout moyen. </div>
                        <div className="text-[28px] font-bold text-dark-blue"><b>Article 8 – DROITS DE L’UTILISATEUR </b></div>
                        <div className="text-[17px] text-dark-blue">Conformément à la réglementation concernant le traitement des données à caractère personnel, l’utilisateur possède les droits ci-après énumérés. Afin que le responsable du traitement des données fasse droit à sa demande, l’utilisateur est tenu de lui communiquer : ses prénom et nom ainsi que son adresse e-mail, et si cela est pertinent, son numéro de compte ou d’espace personnel ou d’abonné. Le responsable du traitement des données est tenu de répondre à l’utilisateur dans un délai de 30 (trente) jours maximum. </div>
                        <div className="text-[22px] font-bold text-dark-blue"><strong>8.1 – PRÉSENTATION DES DROITS DE L’UTILISATEUR EN MATIÈRE DE COLLECTE ET TRAITEMENT DE DONNÉES</strong></div>
                        <div className="text-[17px] text-dark-blue"><strong>1. Droit d’accès, de rectification et droit à l’effacement</strong></div>
                        <div className="text-[17px] text-dark-blue">L’utilisateur peut prendre connaissance, mettre à jour, modifier ou demander la suppression des données le concernant, en respectant la procédure ci-après énoncée : l’utilisateur doit envoyer un email au Délégué à la protection des données, en précisant l’objet de sa demande et en utilisant l’adresse e-mail de contact qui est fournie plus haut. </div>
                        <div className="text-[17px] text-dark-blue"><strong>2. Droit à la portabilité des données</strong></div>
                        <div className="text-[17px] text-dark-blue">L’utilisateur a le droit de demander la portabilité de ses données personnelles, détenues par le site, vers un autre site, en se conformant à la procédure ci-après : l’utilisateur doit faire une demande de portabilité de ses données personnelles auprès du responsable du traitement des données, en envoyant un email à l’adresse prévue ci-dessus. </div>
                        <div className="text-[17px] text-dark-blue"><strong>3. Droit à la limitation et à l’opposition du traitement des données</strong></div>
                        <div className="text-[17px] text-dark-blue">L’utilisateur a le droit de demander la limitation ou de s’opposer au traitement de ses données par le site, sans que le site ne puisse refuser, sauf à démontrer l’existence de motifs légitimes et impérieux, pouvant prévaloir sur les intérêts et les droits et libertés de l’utilisateur. Afin de demander la limitation du traitement de ses données ou de formuler une opposition au traitement de ses données, l’utilisateur doit suivre la procédure suivante : l’utilisateur doit faire une demande de limitation au traitement de ses données personnelles auprès du Délégué à la protection des données, en envoyant un email à l’adresse prévue ci-dessus. L’utilisateur pourrait également exercer son droit d’opposition pour ne plus recevoir la Newsletter en cliquant sur le lien présent en bas de l’email reçu soit à l’adresse </div>
                        <div className="text-[17px] text-dark-blue"><strong>4. Droit de ne pas faire l’objet d’une décision fondée exclusivement sur un procédé automatisé</strong></div>
                        <div className="text-[17px] text-dark-blue">Conformément aux dispositions du règlement 2016/679, l’utilisateur a le droit de ne pas faire l’objet d’une décision fondée exclusivement sur un procédé automatisé si la décision produit des effets juridiques le concernant, ou l’affecte de manière significative de façon similaire. </div>
                        <div className="text-[17px] text-dark-blue"><strong>5. Droit de déterminer le sort des données après la mort</strong></div>
                        <div className="text-[17px] text-dark-blue">Il est rappelé à l’utilisateur qu’il peut organiser quel doit être le devenir de ses données collectées et traitées s’il décède, conformément à la loi n°2016-1321 du 7 octobre 2016. </div>
                        <div className="text-[17px] text-dark-blue"><strong>6. Droit de saisir l’autorité de contrôle compétente</strong></div>
                        <div className="text-[17px] text-dark-blue">Dans le cas où le responsable du traitement des données décide de ne pas répondre à la demande de l’utilisateur, et que l’utilisateur souhaite contester cette décision, ou, s’il pense qu’il est porté atteinte à l’un des droits énumérés ci-dessus, il est en droit de saisir la CNIL (Commission Nationale de l’Informatique et des Libertés, www.cnil.fr) ou tout juge compétent. </div>
                        <div className="text-[17px] text-dark-blue"></div>
                        <div className="text-[28px] font-bold text-dark-blue"><b>Article 9 – DONNÉES PERSONNELLES DES PERSONNES MINEURES </b></div>
                        <div className="text-[17px] text-dark-blue">Conformément aux dispositions de l’article 8 du règlement européen 2016/679 et à la loi Informatique et Libertés, seuls les mineurs âgés de 15 ans ou plus peuvent consentir au traitement de leurs données personnelles. Si l’utilisateur est un mineur de moins de 15 ans, l’accord d’un représentant légal sera requis afin que des données à caractère personnel puissent être collectées et traitées. L’éditeur du site se réserve le droit de vérifier par tout moyen que l’utilisateur est âgé de plus de 15 ans, ou qu’il aura obtenu l’accord d’un représentant légal avant de naviguer sur le site. </div>
                        <div className="text-[28px] font-bold text-dark-blue"><b> Article 10 – Les Cookies </b></div>
                        <div className="text-[17px] text-dark-blue">Un Cookie est un fichier électronique déposé sur un terminal (ordinateur, tablette, smartphone,…) et lu par exemple lors de la consultation d’un site internet, de la lecture d’un courrier électronique, de l’installation ou de l’utilisation d’un logiciel ou d’une application mobile et ce, quel que soit le type de terminal utilisé (source : <span><a className="text-[#0000ff]" href="https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/cookies/que-dit-la-loi">www.cnil.fr/fr/cookies-traceurs-que-dit-la-loi</a></span>). En naviguant sur ce site, des « cookies » émanant du responsable du traitement et/ou des sociétés tiers pourront être déposés sur votre terminal. Lors de la première navigation sur ce site, une bannière explicative sur l’utilisation des « cookies » apparaîtra. Dès lors, en poursuivant la navigation, le client et/ou prospect sera réputé informé et avoir accepté l’utilisation desdits « cookies ». Le consentement donné sera valable pour une période de treize (13) mois. L’utilisateur a la possibilité de désactiver les cookies à partir des paramètres de son navigateur. Ces fichiers lui permettent de traiter des statistiques et des informations sur le trafic, de faciliter la navigation et d’améliorer le service pour le confort de l’utilisateur. Pour l’utilisation de fichiers « cookies » impliquant la sauvegarde et l’analyse de données à caractère personnel, le consentement de l’utilisateur est nécessairement demandé. Il est porté à la connaissance de l’utilisateur qu’il peut s’opposer à l’enregistrement de ces fichiers « cookies » en configurant son logiciel de navigation. Pour information, l’utilisateur peut trouver aux adresses suivantes les démarches à suivre afin de configurer son logiciel de navigation pour s’opposer à l’enregistrement des fichiers « cookies » : -Chrome :  <span><a className="text-[#0000ff]" href="https://support.google.com/accounts/answer/61416?hl=fr">support.google.com/accounts/answer/61416?hl=fr</a></span> -Firefox : <span><a className="text-[#0000ff]" href="https://support.mozilla.org/fr/kb/protection-renforcee-contre-pistage-firefox-ordinateur?redirectslug=autoriser-bloquer-cookies-preferences-sites&redirectlocale=fr">support.mozilla.org/fr/kb/enable-and-disable-cookies-website-preferences</a></span>  -Safari : 
                        <span><a className="text-[#0000ff]" href="https://www.apple.com/legal/privacy/fr-ww/">www.apple.com/legal/privacy/fr-ww/</a> </span> -Internet Explorer : <span><a className="text-[#0000ff]" href="https://support.microsoft.com/fr-fr/windows/supprimer-et-g%C3%A9rer-les-cookies-168dab11-0753-043d-7c16-ede5947fc64d">https://support.microsoft.com/fr-fr/windows/supprimer-et-g%C3%A9rer-les-cookies-168dab11-0753-043d-7c16-ede5947fc64d</a> </span> -Microsoft Edge : <span><a className="text-[#0000ff]" href="http://support.microsoft.com/fr-fr/microsoft-edge/supprimer-les-cookies-dans-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09">support.microsoft.com/fr-fr/microsoft-edge/supprimer-les-cookies-dans-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09</a> </span> -Opera : <span><a className="text-[#0000ff]" href="www.opera.com/help/tutorials/security/cookies/">www.opera.com/help/tutorials/security/cookies/</a> </span> Dans le cas où l’utilisateur décide de désactiver les fichiers « cookies », il pourra poursuivre sa navigation sur le site. Toutefois, tout dysfonctionnement du site provoqué par cette manipulation ne pourrait être considéré comme étant du fait de l’éditeur du site La durée de vie de ces cookies est de treize mois. Pour plus d’informations sur l’utilisation, la gestion et la suppression des « cookies », pour tout type de navigateur, nous vous invitons à consulter le lien suivant : <span><a className="text-[#0000ff]" href="www.cnil.fr/fr/cookies-les-outils-pour-les-maitriser">www.cnil.fr/fr/cookies-les-outils-pour-les-maitriser</a> </span>
                        </div>
                        <div className="text-[28px] font-bold text-dark-blue"><b> Article 11 – CONDITIONS DE MODIFICATION DE LA POLITIQUE DE CONFIDENTIALITÉ </b></div>
                        <div className="text-[17px] text-dark-blue">La présente politique de confidentialité peut être consultée à tout moment sur le site internet. L’éditeur du site se réserve le droit de la modifier afin de garantir sa conformité avec le droit en vigueur. Par conséquent, l’utilisateur est invité à venir consulter régulièrement cette politique de confidentialité afin de se tenir informé des derniers changements qui lui seront apportés. Il est porté à la connaissance de l’utilisateur que la dernière mise à jour de la présente politique de confidentialité est intervenue le 30/06/2022. </div>
                        <div className="text-[28px] font-bold text-dark-blue"><b> Article 12 – ACCEPTATION PAR L’UTILISATEUR DE LA POLITIQUE DE CONFIDENTIALITÉ </b></div>
                        <div className="text-[17px] text-dark-blue">En naviguant sur le site, l’utilisateur atteste avoir lu et compris la présente politique de confidentialité et en accepte les conditions, en ce qui concerne plus particulièrement la collecte et le traitement de ses données à caractère personnel.</div>
                    </div>
                </div>
            </div>
        </div>
    )
}